import Head from 'next/head'
import React from "react";
import App from "./App/App";
import Header from "../components/Header/Header";
import lightMode from "../themes/LightMode";
import { ThemeProvider } from "@material-ui/core";
import { store } from "../redux/store";
import { Provider } from "react-redux";

function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700&display=swap"
              rel="stylesheet"/>
      </Head>

      <main>
        <ThemeProvider theme={lightMode}>
          <Header/>
          <Provider store={store}>
            <App/>
          </Provider>
        </ThemeProvider>
      </main>
    </>
  )
}

export default Home;